title: 지희쓰의 일일 블로그 저장소
description: 데이터 분석가가 되는 그날까지

url:   https://jihuikim45.github.io
image: /images/logo.png

show_downloads: false
future:         true
# timezone:       Asia/Seoul

minima:
  date_format: "%b %-d, %Y"

theme: minima   # ← 이거 꼭 지정!

permalink: /:categories/:title

# social
author: jihuikim45
disqus_shortname:   jihuikim45
google_analytics:   UA-111508093-1

repository: jihuikim45/jihuikim.github.io

highlighter: rouge
markdown:    kramdown
lsi: false
excerpt_separator: "\n\n"
incremental: false

category_dir: categories/
tag_dir: tag/
categories: [android, aws, data_science, git, jekyll, linux, machine-learning, python, pytorch, review, synology, thoughts]

paginate: 10
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

include:
  - _pages

exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

collections:
  posts:
    output: true

defaults:                     # ← 요 블럭 꼭 추가!!
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: ""
    values:
      css: "/assets/css/custom.css"